### ISSUE TITLE
[Question] Why msg, not srv?

### ISSUE THREAD

**Issue by seiya0412** [joshs333/bag_recorder#2]
Hi, thank you for a great package.

I'm trying to add a little modification on my fork of this package so that I can use this in my project, and I have a little quick question.
What is the reason for you to use messages to start/stop recording instead of service call?
In my personal opinion, using service call is more natural for "one-shot trigger" than using messages, but I'd like to understand your design philosophy first.

Thank you!

**Comment by joshs333** [comment]
Hello;

The reason I used a message was mostly due to the philosophy of the lab I was working in at the time, who preferred topic calls to service calls to allow it to be seen via rostopic echo and recorded to bags in itself.

I agree service calls are better for triggers and given the time would likely return and add a service call trigger as well as the topic trigger. If you opened a request I wouldn't mind doing this for you over the weekend. If you implemented it and wouldn't mind merging it back in I would also love to do that.

Also, I'm very glad you are getting use from the package. Feel free to ask other questions or close this 'issue' when you feel your questions are resolved.

**Comment by joshs333** [comment]
@seiya0412 I see you have implemented this in your fork. I again invite you to close the fork if you feel this is resolved, otherwise feel free to comment how else I can support you with this or I will probably close this in a week or so.

I've enjoyed taking a look at your fork, nice to see you could evolve the code into something better to fit your needs :)
